#include <stdio.h>

#define CONF_LOG_TAG_INCLUDE

#define CONF_LOG_TAG_TRACE_PREFIX  "["
#define CONF_LOG_TAG_TRACE_POSTFIX "]"
#define CONF_LOG_TAG_TRACE_TEXT    "TRACE"
#define CONF_LOG_TAG_TRACE_COLOR   CONF_LOG_RED
#define CONF_LOG_TAG_TRACE_ATTR    CONF_LOG_BOLD

#define CONF_LOG_TAG_DEBUG_PREFIX  "("
#define CONF_LOG_TAG_DEBUG_POSTFIX ")"
#define CONF_LOG_TAG_DEBUG_TEXT    "DEBUG"
#define CONF_LOG_TAG_DEBUG_COLOR   CONF_LOG_GREEN
#define CONF_LOG_TAG_DEBUG_ATTR    CONF_LOG_BOLD

#define CONF_LOG_TAG_INFO_PREFIX  "*"
#define CONF_LOG_TAG_INFO_POSTFIX "*"
#define CONF_LOG_TAG_INFO_TEXT    "inform"
#define CONF_LOG_TAG_INFO_COLOR   CONF_LOG_BLUE
#define CONF_LOG_TAG_INFO_ATTR    CONF_LOG_HIGH_INTENSITY

#define CONF_LOG_TAG_WARN_PREFIX  "^"
#define CONF_LOG_TAG_WARN_POSTFIX "^"
#define CONF_LOG_TAG_WARN_TEXT    "WARN"
#define CONF_LOG_TAG_WARN_COLOR   CONF_LOG_CYAN
#define CONF_LOG_TAG_WARN_ATTR    CONF_LOG_UNDERLINE

#define CONF_LOG_TAG_ERROR_PREFIX  ""
#define CONF_LOG_TAG_ERROR_POSTFIX "?"
#define CONF_LOG_TAG_ERROR_TEXT    "ERROR"
#define CONF_LOG_TAG_ERROR_COLOR   CONF_LOG_PURPLE
#define CONF_LOG_TAG_ERROR_ATTR    CONF_LOG_HIGH_INTENSITY_BOLD

#define CONF_LOG_TAG_FATAL_PREFIX  "%"
#define CONF_LOG_TAG_FATAL_POSTFIX "%"
#define CONF_LOG_TAG_FATAL_TEXT    "fATaL"
#define CONF_LOG_TAG_FATAL_COLOR   CONF_LOG_BLACK
#define CONF_LOG_TAG_FATAL_ATTR    CONF_LOG_HIGH_INTENSITY_BACKGROUND

#define CONF_LOG_MSG_PREFIX  ""
#define CONF_LOG_MSG_POSTFIX ""
#define CONF_LOG_MSG_COLOR   CONF_LOG_WHITE
#define CONF_LOG_MSG_ATTR    CONF_LOG_REGULAR

#define CONF_LOG_INCLUDE_FILENAME

#define CONF_LOG_INCLUDE_FILENUM

//
//
//
//
//

#define CONF_LOG_BLACK  0
#define CONF_LOG_RED    1
#define CONF_LOG_GREEN  2
#define CONF_LOG_YELLOW 3
#define CONF_LOG_BLUE   4
#define CONF_LOG_PURPLE 5
#define CONF_LOG_CYAN   6
#define CONF_LOG_WHITE  7

#define CONF_LOG_REGULAR                   0
#define CONF_LOG_BOLD                      1
#define CONF_LOG_UNDERLINE                 2
#define CONF_LOG_BACKGROUND                3
#define CONF_LOG_HIGH_INTENSITY            4
#define CONF_LOG_HIGH_INTENSITY_BOLD       5
#define CONF_LOG_HIGH_INTENSITY_BACKGROUND 6

#define CONF_LOG_REGULAR_BLACK  "\e[0;30m"
#define CONF_LOG_REGULAR_RED    "\e[0;31m"
#define CONF_LOG_REGULAR_GREEN  "\e[0;32m"
#define CONF_LOG_REGULAR_YELLOW "\e[0;33m"
#define CONF_LOG_REGULAR_BLUE   "\e[0;34m"
#define CONF_LOG_REGULAR_PURPLE "\e[0;35m"
#define CONF_LOG_REGULAR_CYAN   "\e[0;36m"
#define CONF_LOG_REGULAR_WHITE  "\e[0;37m"

#define CONF_LOG_BOLD_BLACK  "\e[1;30m"
#define CONF_LOG_BOLD_RED    "\e[1;31m"
#define CONF_LOG_BOLD_GREEN  "\e[1;32m"
#define CONF_LOG_BOLD_YELLOW "\e[1;33m"
#define CONF_LOG_BOLD_BLUE   "\e[1;34m"
#define CONF_LOG_BOLD_PURPLE "\e[1;35m"
#define CONF_LOG_BOLD_CYAN   "\e[1;36m"
#define CONF_LOG_BOLD_WHITE  "\e[1;37m"

#define CONF_LOG_UNDERLINE_BLACK  "\e[4;30m"
#define CONF_LOG_UNDERLINE_RED    "\e[4;31m"
#define CONF_LOG_UNDERLINE_GREEN  "\e[4;32m"
#define CONF_LOG_UNDERLINE_YELLOW "\e[4;33m"
#define CONF_LOG_UNDERLINE_BLUE   "\e[4;34m"
#define CONF_LOG_UNDERLINE_PURPLE "\e[4;35m"
#define CONF_LOG_UNDERLINE_CYAN   "\e[4;36m"
#define CONF_LOG_UNDERLINE_WHITE  "\e[4;37m"

#define CONF_LOG_BACKGROUND_BLACK  "\e[40m"
#define CONF_LOG_BACKGROUND_RED    "\e[41m"
#define CONF_LOG_BACKGROUND_GREEN  "\e[42m"
#define CONF_LOG_BACKGROUND_YELLOW "\e[43m"
#define CONF_LOG_BACKGROUND_BLUE   "\e[44m"
#define CONF_LOG_BACKGROUND_PURPLE "\e[45m"
#define CONF_LOG_BACKGROUND_CYAN   "\e[46m"
#define CONF_LOG_BACKGROUND_WHITE  "\e[47m"

#define CONF_LOG_HIGH_INTENSITY_BLACK  "\e[0;90m"
#define CONF_LOG_HIGH_INTENSITY_RED    "\e[0;91m"
#define CONF_LOG_HIGH_INTENSITY_GREEN  "\e[0;92m"
#define CONF_LOG_HIGH_INTENSITY_YELLOW "\e[0;93m"
#define CONF_LOG_HIGH_INTENSITY_BLUE   "\e[0;94m"
#define CONF_LOG_HIGH_INTENSITY_PURPLE "\e[0;95m"
#define CONF_LOG_HIGH_INTENSITY_CYAN   "\e[0;96m"
#define CONF_LOG_HIGH_INTENSITY_WHITE  "\e[0;97m"

#define CONF_LOG_HIGH_INTENSITY_BOLD_BLACK  "\e[1;90m"
#define CONF_LOG_HIGH_INTENSITY_BOLD_RED    "\e[1;91m"
#define CONF_LOG_HIGH_INTENSITY_BOLD_GREEN  "\e[1;92m"
#define CONF_LOG_HIGH_INTENSITY_BOLD_YELLOW "\e[1;93m"
#define CONF_LOG_HIGH_INTENSITY_BOLD_BLUE   "\e[1;94m"
#define CONF_LOG_HIGH_INTENSITY_BOLD_PURPLE "\e[1;95m"
#define CONF_LOG_HIGH_INTENSITY_BOLD_CYAN   "\e[1;96m"
#define CONF_LOG_HIGH_INTENSITY_BOLD_WHITE  "\e[1;97m"

#define CONF_LOG_HIGH_INTENSITY_BACKGROUND_BLACK  "\e[0;100m"
#define CONF_LOG_HIGH_INTENSITY_BACKGROUND_RED    "\e[0;101m"
#define CONF_LOG_HIGH_INTENSITY_BACKGROUND_GREEN  "\e[0;102m"
#define CONF_LOG_HIGH_INTENSITY_BACKGROUND_YELLOW "\e[0;103m"
#define CONF_LOG_HIGH_INTENSITY_BACKGROUND_BLUE   "\e[0;104m"
#define CONF_LOG_HIGH_INTENSITY_BACKGROUND_PURPLE "\e[0;105m"
#define CONF_LOG_HIGH_INTENSITY_BACKGROUND_CYAN   "\e[0;106m"
#define CONF_LOG_HIGH_INTENSITY_BACKGROUND_WHITE  "\e[0;107m"

#define CONF_LOG_RESET "\e[0m"

#ifndef CONF_LOG_TAG_INCLUDE

#define CONF_LOG_TAG_TRACE_FORMAT ""
#define CONF_LOG_TAG_DEBUG_FORMAT ""
#define CONF_LOG_TAG_INFO_FORMAT  ""
#define CONF_LOG_TAG_WARN_FORMAT  ""
#define CONF_LOG_TAG_ERROR_FORMAT ""
#define CONF_LOG_TAG_FATAL_FORMAT ""

#else

#ifndef CONF_LOG_TAG_TRACE_PREFIX
#define CONF_LOG_TAG_TRACE_PREFIX ""
#endif

#ifndef CONF_LOG_TAG_TRACE_POSTFIX
#define CONF_LOG_TAG_TRACE_POSTFIX ""
#endif

#ifndef CONF_LOG_TAG_TRACE_TEXT
#define CONF_LOG_TAG_TRACE_TEXT "trace"
#endif

#ifdef CONF_LOG_TAG_TRACE_COLOR
#ifdef CONF_LOG_TAG_TRACE_ATTR

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_REGULAR_BLACK CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_BOLD_BLACK CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_UNDERLINE_BLACK CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_BACKGROUND_BLACK CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BLACK CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_BLACK CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_BLACK CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_RED && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_REGULAR_RED CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_RED && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_BOLD_RED CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_RED && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_UNDERLINE_RED CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_RED && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_BACKGROUND_RED CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_RED && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_RED CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_RED && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_RED CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_RED && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_RED CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_REGULAR_GREEN CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_BOLD_GREEN CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_UNDERLINE_GREEN CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_BACKGROUND_GREEN CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_GREEN CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_GREEN CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_GREEN CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_REGULAR_YELLOW CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_BOLD_YELLOW CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_UNDERLINE_YELLOW CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_BACKGROUND_YELLOW CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_YELLOW CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_YELLOW CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_YELLOW CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_REGULAR_BLUE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_BOLD_BLUE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_UNDERLINE_BLUE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_BACKGROUND_BLUE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BLUE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_BLUE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_BLUE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_REGULAR_PURPLE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_BOLD_PURPLE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_UNDERLINE_PURPLE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_BACKGROUND_PURPLE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_PURPLE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_PURPLE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_PURPLE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_REGULAR_CYAN CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_BOLD_CYAN CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_UNDERLINE_CYAN CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_BACKGROUND_CYAN CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_CYAN CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_CYAN CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_CYAN CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_REGULAR_WHITE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_BOLD_WHITE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_UNDERLINE_WHITE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_BACKGROUND_WHITE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_WHITE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_WHITE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#if CONF_LOG_TAG_TRACE_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_TRACE_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_WHITE CONF_LOG_TAG_TRACE_TEXT CONF_LOG_RESET CONF_LOG_TAG_TRACE_POSTFIX
#endif

#endif
#endif

#ifndef CONF_LOG_TAG_TRACE_COLOR
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_TAG_TRACE_TEXT CONF_LOG_TAG_TRACE_POSTFIX
#endif

#ifndef CONF_LOG_TAG_TRACE_ATTR
#define CONF_LOG_TAG_TRACE_FORMAT CONF_LOG_TAG_TRACE_PREFIX CONF_LOG_TAG_TRACE_TEXT CONF_LOG_TAG_TRACE_POSTFIX
#endif

#ifndef CONF_LOG_TAG_TRACE_FORMAT
#error "something went wrong"
#endif

#ifndef CONF_LOG_TAG_DEBUG_PREFIX
#define CONF_LOG_TAG_DEBUG_PREFIX ""
#endif

#ifndef CONF_LOG_TAG_DEBUG_POSTFIX
#define CONF_LOG_TAG_DEBUG_POSTFIX ""
#endif

#ifndef CONF_LOG_TAG_DEBUG_TEXT
#define CONF_LOG_TAG_DEBUG_TEXT "debug"
#endif

#ifdef CONF_LOG_TAG_DEBUG_COLOR
#ifdef CONF_LOG_TAG_DEBUG_ATTR

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_REGULAR_BLACK CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_BOLD_BLACK CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_UNDERLINE_BLACK CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_BACKGROUND_BLACK CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BLACK CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_BLACK CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_BLACK CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_RED && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_REGULAR_RED CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_RED && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_BOLD_RED CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_RED && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_UNDERLINE_RED CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_RED && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_BACKGROUND_RED CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_RED && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_RED CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_RED && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_RED CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_RED && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_RED CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_REGULAR_GREEN CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_BOLD_GREEN CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_UNDERLINE_GREEN CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_BACKGROUND_GREEN CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_GREEN CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_GREEN CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_GREEN CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_REGULAR_YELLOW CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_BOLD_YELLOW CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_UNDERLINE_YELLOW CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_BACKGROUND_YELLOW CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_YELLOW CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_YELLOW CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_YELLOW CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_REGULAR_BLUE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_BOLD_BLUE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_UNDERLINE_BLUE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_BACKGROUND_BLUE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BLUE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_BLUE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_BLUE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_REGULAR_PURPLE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_BOLD_PURPLE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_UNDERLINE_PURPLE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_BACKGROUND_PURPLE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_PURPLE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_PURPLE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_PURPLE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_REGULAR_CYAN CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_BOLD_CYAN CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_UNDERLINE_CYAN CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_BACKGROUND_CYAN CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_CYAN CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_CYAN CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_CYAN CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_REGULAR_WHITE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_BOLD_WHITE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_UNDERLINE_WHITE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_BACKGROUND_WHITE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_WHITE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_WHITE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#if CONF_LOG_TAG_DEBUG_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_DEBUG_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_WHITE CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_RESET CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#endif
#endif

#ifndef CONF_LOG_TAG_DEBUG_COLOR
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#ifndef CONF_LOG_TAG_DEBUG_ATTR
#define CONF_LOG_TAG_DEBUG_FORMAT CONF_LOG_TAG_DEBUG_PREFIX CONF_LOG_TAG_DEBUG_TEXT CONF_LOG_TAG_DEBUG_POSTFIX
#endif

#ifndef CONF_LOG_TAG_DEBUG_FORMAT
#error "something went wrong"
#endif

#ifndef CONF_LOG_TAG_INFO_PREFIX
#define CONF_LOG_TAG_INFO_PREFIX ""
#endif

#ifndef CONF_LOG_TAG_INFO_POSTFIX
#define CONF_LOG_TAG_INFO_POSTFIX ""
#endif

#ifndef CONF_LOG_TAG_INFO_TEXT
#define CONF_LOG_TAG_INFO_TEXT "info"
#endif

#ifdef CONF_LOG_TAG_INFO_COLOR
#ifdef CONF_LOG_TAG_INFO_ATTR

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_REGULAR_BLACK CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_BOLD_BLACK CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_UNDERLINE_BLACK CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_BACKGROUND_BLACK CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BLACK CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_BLACK CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_BLACK CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_RED && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_REGULAR_RED CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_RED && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_BOLD_RED CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_RED && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_UNDERLINE_RED CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_RED && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_BACKGROUND_RED CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_RED && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_RED CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_RED && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_RED CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_RED && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_RED CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_REGULAR_GREEN CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_BOLD_GREEN CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_UNDERLINE_GREEN CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_BACKGROUND_GREEN CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_GREEN CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_GREEN CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_GREEN CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_REGULAR_YELLOW CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_BOLD_YELLOW CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_UNDERLINE_YELLOW CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_BACKGROUND_YELLOW CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_YELLOW CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_YELLOW CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_YELLOW CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_REGULAR_BLUE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_BOLD_BLUE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_UNDERLINE_BLUE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_BACKGROUND_BLUE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BLUE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_BLUE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_BLUE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_REGULAR_PURPLE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_BOLD_PURPLE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_UNDERLINE_PURPLE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_BACKGROUND_PURPLE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_PURPLE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_PURPLE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_PURPLE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_REGULAR_CYAN CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_BOLD_CYAN CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_UNDERLINE_CYAN CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_BACKGROUND_CYAN CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_CYAN CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_CYAN CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_CYAN CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_REGULAR_WHITE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_BOLD_WHITE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_UNDERLINE_WHITE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_BACKGROUND_WHITE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_WHITE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_WHITE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#if CONF_LOG_TAG_INFO_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_INFO_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_WHITE CONF_LOG_TAG_INFO_TEXT CONF_LOG_RESET CONF_LOG_TAG_INFO_POSTFIX
#endif

#endif
#endif

#ifndef CONF_LOG_TAG_INFO_COLOR
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_TAG_INFO_TEXT CONF_LOG_TAG_INFO_POSTFIX
#endif

#ifndef CONF_LOG_TAG_INFO_ATTR
#define CONF_LOG_TAG_INFO_FORMAT CONF_LOG_TAG_INFO_PREFIX CONF_LOG_TAG_INFO_TEXT CONF_LOG_TAG_INFO_POSTFIX
#endif

#ifndef CONF_LOG_TAG_INFO_FORMAT
#error "something went wrong"
#endif

#ifndef CONF_LOG_TAG_WARN_PREFIX
#define CONF_LOG_TAG_WARN_PREFIX ""
#endif

#ifndef CONF_LOG_TAG_WARN_POSTFIX
#define CONF_LOG_TAG_WARN_POSTFIX ""
#endif

#ifndef CONF_LOG_TAG_WARN_TEXT
#define CONF_LOG_TAG_WARN_TEXT "warn"
#endif

#ifdef CONF_LOG_TAG_WARN_COLOR
#ifdef CONF_LOG_TAG_WARN_ATTR

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_REGULAR_BLACK CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_BOLD_BLACK CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_UNDERLINE_BLACK CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_BACKGROUND_BLACK CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BLACK CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_BLACK CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_BLACK CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_RED && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_REGULAR_RED CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_RED && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_BOLD_RED CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_RED && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_UNDERLINE_RED CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_RED && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_BACKGROUND_RED CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_RED && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_RED CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_RED && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_RED CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_RED && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_RED CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_REGULAR_GREEN CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_BOLD_GREEN CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_UNDERLINE_GREEN CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_BACKGROUND_GREEN CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_GREEN CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_GREEN CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_GREEN CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_REGULAR_YELLOW CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_BOLD_YELLOW CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_UNDERLINE_YELLOW CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_BACKGROUND_YELLOW CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_YELLOW CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_YELLOW CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_YELLOW CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_REGULAR_BLUE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_BOLD_BLUE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_UNDERLINE_BLUE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_BACKGROUND_BLUE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BLUE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_BLUE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_BLUE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_REGULAR_PURPLE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_BOLD_PURPLE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_UNDERLINE_PURPLE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_BACKGROUND_PURPLE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_PURPLE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_PURPLE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_PURPLE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_REGULAR_CYAN CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_BOLD_CYAN CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_UNDERLINE_CYAN CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_BACKGROUND_CYAN CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_CYAN CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_CYAN CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_CYAN CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_REGULAR_WHITE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_BOLD_WHITE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_UNDERLINE_WHITE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_BACKGROUND_WHITE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_WHITE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_WHITE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#if CONF_LOG_TAG_WARN_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_WARN_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_WHITE CONF_LOG_TAG_WARN_TEXT CONF_LOG_RESET CONF_LOG_TAG_WARN_POSTFIX
#endif

#endif
#endif

#ifndef CONF_LOG_TAG_WARN_COLOR
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_TAG_WARN_TEXT CONF_LOG_TAG_WARN_POSTFIX
#endif

#ifndef CONF_LOG_TAG_WARN_ATTR
#define CONF_LOG_TAG_WARN_FORMAT CONF_LOG_TAG_WARN_PREFIX CONF_LOG_TAG_WARN_TEXT CONF_LOG_TAG_WARN_POSTFIX
#endif

#ifndef CONF_LOG_TAG_WARN_FORMAT
#error "something went wrong"
#endif

#ifndef CONF_LOG_TAG_ERROR_PREFIX
#define CONF_LOG_TAG_ERROR_PREFIX ""
#endif

#ifndef CONF_LOG_TAG_ERROR_POSTFIX
#define CONF_LOG_TAG_ERROR_POSTFIX ""
#endif

#ifndef CONF_LOG_TAG_ERROR_TEXT
#define CONF_LOG_TAG_ERROR_TEXT "error"
#endif

#ifdef CONF_LOG_TAG_ERROR_COLOR
#ifdef CONF_LOG_TAG_ERROR_ATTR

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_REGULAR_BLACK CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_BOLD_BLACK CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_UNDERLINE_BLACK CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_BACKGROUND_BLACK CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BLACK CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_BLACK CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_BLACK CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_RED && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_REGULAR_RED CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_RED && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_BOLD_RED CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_RED && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_UNDERLINE_RED CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_RED && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_BACKGROUND_RED CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_RED && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_RED CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_RED && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_RED CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_RED && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_RED CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_REGULAR_GREEN CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_BOLD_GREEN CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_UNDERLINE_GREEN CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_BACKGROUND_GREEN CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_GREEN CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_GREEN CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_GREEN CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_REGULAR_YELLOW CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_BOLD_YELLOW CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_UNDERLINE_YELLOW CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_BACKGROUND_YELLOW CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_YELLOW CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_YELLOW CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_YELLOW CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_REGULAR_BLUE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_BOLD_BLUE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_UNDERLINE_BLUE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_BACKGROUND_BLUE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BLUE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_BLUE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_BLUE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_REGULAR_PURPLE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_BOLD_PURPLE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_UNDERLINE_PURPLE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_BACKGROUND_PURPLE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_PURPLE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_PURPLE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_PURPLE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_REGULAR_CYAN CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_BOLD_CYAN CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_UNDERLINE_CYAN CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_BACKGROUND_CYAN CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_CYAN CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_CYAN CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_CYAN CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_REGULAR_WHITE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_BOLD_WHITE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_UNDERLINE_WHITE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_BACKGROUND_WHITE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_WHITE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_WHITE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#if CONF_LOG_TAG_ERROR_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_ERROR_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_WHITE CONF_LOG_TAG_ERROR_TEXT CONF_LOG_RESET CONF_LOG_TAG_ERROR_POSTFIX
#endif

#endif
#endif

#ifndef CONF_LOG_TAG_ERROR_COLOR
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_TAG_ERROR_TEXT CONF_LOG_TAG_ERROR_POSTFIX
#endif

#ifndef CONF_LOG_TAG_ERROR_ATTR
#define CONF_LOG_TAG_ERROR_FORMAT CONF_LOG_TAG_ERROR_PREFIX CONF_LOG_TAG_ERROR_TEXT CONF_LOG_TAG_ERROR_POSTFIX
#endif

#ifndef CONF_LOG_TAG_ERROR_FORMAT
#error "something went wrong"
#endif

#ifndef CONF_LOG_TAG_FATAL_PREFIX
#define CONF_LOG_TAG_FATAL_PREFIX ""
#endif

#ifndef CONF_LOG_TAG_FATAL_POSTFIX
#define CONF_LOG_TAG_FATAL_POSTFIX ""
#endif

#ifndef CONF_LOG_TAG_FATAL_TEXT
#define CONF_LOG_TAG_FATAL_TEXT "fatal"
#endif

#ifdef CONF_LOG_TAG_FATAL_COLOR
#ifdef CONF_LOG_TAG_FATAL_ATTR

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_REGULAR_BLACK CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_BOLD_BLACK CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_UNDERLINE_BLACK CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_BACKGROUND_BLACK CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BLACK CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_BLACK CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_BLACK && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_BLACK CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_RED && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_REGULAR_RED CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_RED && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_BOLD_RED CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_RED && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_UNDERLINE_RED CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_RED && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_BACKGROUND_RED CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_RED && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_RED CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_RED && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_RED CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_RED && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_RED CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_REGULAR_GREEN CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_BOLD_GREEN CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_UNDERLINE_GREEN CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_BACKGROUND_GREEN CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_GREEN CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_GREEN CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_GREEN && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_GREEN CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_REGULAR_YELLOW CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_BOLD_YELLOW CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_UNDERLINE_YELLOW CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_BACKGROUND_YELLOW CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_YELLOW CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_YELLOW CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_YELLOW && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_YELLOW CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_REGULAR_BLUE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_BOLD_BLUE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_UNDERLINE_BLUE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_BACKGROUND_BLUE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BLUE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_BLUE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_BLUE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_BLUE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_REGULAR_PURPLE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_BOLD_PURPLE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_UNDERLINE_PURPLE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_BACKGROUND_PURPLE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_PURPLE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_PURPLE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_PURPLE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_PURPLE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_REGULAR_CYAN CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_BOLD_CYAN CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_UNDERLINE_CYAN CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_BACKGROUND_CYAN CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_CYAN CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_CYAN CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_CYAN && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_CYAN CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_REGULAR
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_REGULAR_WHITE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_BOLD
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_BOLD_WHITE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_UNDERLINE
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_UNDERLINE_WHITE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_BACKGROUND
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_BACKGROUND_WHITE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_WHITE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY_BOLD
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BOLD_WHITE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#if CONF_LOG_TAG_FATAL_COLOR == CONF_LOG_WHITE && CONF_LOG_TAG_FATAL_ATTR == CONF_LOG_HIGH_INTENSITY_BACKGROUND
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_HIGH_INTENSITY_BACKGROUND_WHITE CONF_LOG_TAG_FATAL_TEXT CONF_LOG_RESET CONF_LOG_TAG_FATAL_POSTFIX
#endif

#endif
#endif

#ifndef CONF_LOG_TAG_FATAL_COLOR
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_TAG_FATAL_TEXT CONF_LOG_TAG_FATAL_POSTFIX
#endif

#ifndef CONF_LOG_TAG_FATAL_ATTR
#define CONF_LOG_TAG_FATAL_FORMAT CONF_LOG_TAG_FATAL_PREFIX CONF_LOG_TAG_FATAL_TEXT CONF_LOG_TAG_FATAL_POSTFIX
#endif

#ifndef CONF_LOG_TAG_FATAL_FORMAT
#error "something went wrong"
#endif

#endif

int main(int argc, char** argv) {
  printf("%s\n", CONF_LOG_TAG_TRACE_FORMAT);
  printf("%s\n", CONF_LOG_TAG_DEBUG_FORMAT);
  printf("%s\n", CONF_LOG_TAG_INFO_FORMAT);
  printf("%s\n", CONF_LOG_TAG_WARN_FORMAT);
  printf("%s\n", CONF_LOG_TAG_ERROR_FORMAT);
  printf("%s\n", CONF_LOG_TAG_FATAL_FORMAT);

  return 0;
}
