#ifndef CONF_LOG_CONF_H
#define CONF_LOG_CONF_H

#define CONF_LOG_LEVEL CONF_LOG_TRACE

#define CONF_LOG_PREFIX  ""
#define CONF_LOG_POSTFIX "\n"

#define CONF_LOG_TIME_INCLUDE
#define CONF_LOG_TIME_INDEX    0
#define CONF_LOG_TIME_PREFIX   ""
#define CONF_LOG_TIME_POSTFIX  " "
#define CONF_LOG_TIME_STYLE    "%I:%M:%S"
#define CONF_LOG_TIME_MAX_SIZE 128
#define CONF_LOG_TIME_COLOR    CONF_LOG_WHITE
#define CONF_LOG_TIME_ATTR     CONF_LOG_BOLD

#define CONF_LOG_TAG_INCLUDE
#define CONF_LOG_TAG_INDEX 1

#define CONF_LOG_TAG_TRACE_PREFIX  ""
#define CONF_LOG_TAG_TRACE_POSTFIX " "
#define CONF_LOG_TAG_TRACE_TEXT    "TRACE"
#define CONF_LOG_TAG_TRACE_COLOR   CONF_LOG_GREEN
#define CONF_LOG_TAG_TRACE_ATTR    CONF_LOG_REGULAR

#define CONF_LOG_TAG_DEBUG_PREFIX  ""
#define CONF_LOG_TAG_DEBUG_POSTFIX " "
#define CONF_LOG_TAG_DEBUG_TEXT    "DEBUG"
#define CONF_LOG_TAG_DEBUG_COLOR   CONF_LOG_GREEN
#define CONF_LOG_TAG_DEBUG_ATTR    CONF_LOG_BOLD

#define CONF_LOG_TAG_INFO_PREFIX  ""
#define CONF_LOG_TAG_INFO_POSTFIX "  "
#define CONF_LOG_TAG_INFO_TEXT    "INFO"
#define CONF_LOG_TAG_INFO_COLOR   CONF_LOG_YELLOW
#define CONF_LOG_TAG_INFO_ATTR    CONF_LOG_REGULAR

#define CONF_LOG_TAG_WARN_PREFIX  ""
#define CONF_LOG_TAG_WARN_POSTFIX "  "
#define CONF_LOG_TAG_WARN_TEXT    "WARN"
#define CONF_LOG_TAG_WARN_COLOR   CONF_LOG_YELLOW
#define CONF_LOG_TAG_WARN_ATTR    CONF_LOG_BOLD

#define CONF_LOG_TAG_ERROR_PREFIX  ""
#define CONF_LOG_TAG_ERROR_POSTFIX " "
#define CONF_LOG_TAG_ERROR_TEXT    "ERROR"
#define CONF_LOG_TAG_ERROR_COLOR   CONF_LOG_RED
#define CONF_LOG_TAG_ERROR_ATTR    CONF_LOG_HIGH_INTENSITY_BOLD

#define CONF_LOG_TAG_FATAL_PREFIX  ""
#define CONF_LOG_TAG_FATAL_POSTFIX " "
#define CONF_LOG_TAG_FATAL_TEXT    "FATAL"
#define CONF_LOG_TAG_FATAL_COLOR   CONF_LOG_RED
#define CONF_LOG_TAG_FATAL_ATTR    CONF_LOG_HIGH_INTENSITY_BACKGROUND

#define CONF_LOG_FILE_INFO_INCLUDE
#define CONF_LOG_FILE_INFO_INDEX   2
#define CONF_LOG_FILE_INFO_PREFIX  "("
#define CONF_LOG_FILE_INFO_POSTFIX ") "
#define CONF_LOG_FILE_INFO_COLOR   CONF_LOG_WHITE
#define CONF_LOG_FILE_INFO_ATTR    CONF_LOG_REGULAR

#define CONF_LOG_MSG_INCLUDE
#define CONF_LOG_MSG_INDEX   3
#define CONF_LOG_MSG_PREFIX  ""
#define CONF_LOG_MSG_POSTFIX ""
#define CONF_LOG_MSG_COLOR   CONF_LOG_WHITE
#define CONF_LOG_MSG_ATTR    CONF_LOG_HIGH_INTENSITY_BOLD

#define CONF_LOG_TAG_TRACE_PRINT_FUNC(fmt, args...) \
  printf(fmt, ##args)

#define CONF_LOG_TAG_DEBUG_PRINT_FUNC(fmt, args...) \
  printf(fmt, ##args)

#define CONF_LOG_TAG_INFO_PRINT_FUNC(fmt, args...) \
  printf(fmt, ##args)

#define CONF_LOG_TAG_WARN_PRINT_FUNC(fmt, args...) \
  fprintf(stderr, fmt, ##args)

#define CONF_LOG_TAG_ERROR_PRINT_FUNC(fmt, args...) \
  fprintf(stderr, fmt, ##args)

#define CONF_LOG_TAG_FATAL_PRINT_FUNC(fmt, args...) \
  fprintf(stderr, fmt, ##args)

#include "conf-log.h"

#endif